dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: ISq/F2s7ZKJZMhTna6U+ktAf6Vv57e4jkfSol+UkQmKe3713kZi9L5CjolyhzqFLzVUXSOgoPLMbq30mlzlUaq5EcY/3Gthhx36sYvK5lc/3T0b7fXINAP0sCdvCZhleIQf2n0xp2zbweL+BuGrIiPNeVMppe15CRrakPL4gFN/XBvWf+XEG0irWKmAYc2khgR2CNrJGpaLXq7CUNpaJNc+a+AZ2zUzsI2+Es9We2gD/eTf81wYVqhGWoVRvJIN50wZtJPxjTiRQ04R5aoEAG5rCtVuF/rGu4BYI0FrWTWfmkPlpr2agDmOooNaVx9cG71AsxRLRhcvKTGNNzfCbmvuZ8CJbBqwl/pqknBKRp2bRU9Gpw1dYXN3QFpNbk/XGIw6Rq6x37amBfB9kzbK1eN9bLMyzcl3ubcbGeempWxmRfo0XONGTCcz5uM+vitL5C0TrjGa77cThpJ/fvhDPC0vFIALfDzN2+qvM2rJLz2PEOvpVsC9hCATtuj0SeAcOxkBbJgAj/CbNHg+pS5Izb8C/ECfygy/pLqkCmxAndpmwPLHywqU2kqtIBjO/qVvdNoXWojqAebX7kd7Q/JvqP1T8BRyLEyUhWBFMUFOAoGs38L4AuV10PydV8a++Bbb2Gklt2I7yw3nZGJYmfLTlCyBjEXnjWs9R6LPDcTKE2hU=
