version: '3.3'

services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
        - comment_db
        - post_db

  ui:
    image: ${USER_NAME}/ui:${UI_TAG:-1.0}
    ports:
      - ${UI_PORT:-9292}:9292/tcp
    networks:
      - frontend
      
  post:
    image: ${USER_NAME}/post:${POST_TAG:-1.0}
    networks:
      - frontend
      - backend

  comment:
    image: ${USER_NAME}/comment:${COMMENT_TAG:-1.0}
    networks:
      - frontend
      - backend

volumes:
  post_db:

networks:
  backend:
  frontend:
