version: '3.3'

services:
  db:
    image: mongo:3.2
    volumes:
      - db:/data/db
    networks:
      - reddit
  app:    
    image: ${USERNAME}/reddit:${TAG:-1.0}
    ports:
      - ${UI_PORT:-9292}:9292/tcp
    networks:
      - reddit
    depends_on:
      - db
    environment:
      DATABASE_URL: db

volumes:
  db:

networks:
  reddit:
