- name: Create GCP resources
  hosts: localhost
  gather_facts: no
  tags: create
  vars_files:
    - "{{ lookup('env', 'PWD') }}/files/env-vars.yml"


  tasks:
    - name: Create an ext IP address for loadbalancing
      gcp_compute_address:
        name: "{{ cluster_name }}"
        region: "{{ region }}"
        project: "{{ project }}"
        service_account_file: "{{ cred_file }}"
        auth_kind: "{{ cred_kind }}"
      register: ext_ip

    - name: Create a network
      gcp_compute_network:
        name: "{{ cluster_name }}"
        auto_create_subnetworks: 'false'
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: present
      register: network

    - name: Create a subnetwork
      gcp_compute_subnetwork:
        name: kubernetes
        region: "{{ region }}"
        network: "{{ network }}"
        ip_cidr_range: 10.240.0.0/24
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: present
      register: subnetwork

    - name: Create kubernetes-the-hard-way-allow-internal firewall rule
      gcp_compute_firewall:
        name: kubernetes-the-hard-way-allow-internal
        network: "{{ network }}"
        allowed:
        - ip_protocol: tcp
        - ip_protocol: udp
        - ip_protocol: icmp
        source_ranges:
        - 10.240.0.0/24
        - 10.200.0.0/16
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: present

    - name: Create kubernetes-the-hard-way-allow-external firewall rule
      gcp_compute_firewall:
        name: kubernetes-the-hard-way-allow-external
        network: "{{ network }}"
        allowed:
        - ip_protocol: tcp
          ports:
          - "22"
          - "6443"
        - ip_protocol: icmp
        source_ranges:
        - 0.0.0.0/0
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: present

    - name: Create kubernetes-the-hard-way-allow-health-check firewall rule
      gcp_compute_firewall:
        name: kubernetes-the-hard-way-allow-health-check
        network: "{{ network }}"
        allowed:
        - ip_protocol: tcp
        source_ranges:
        - "209.85.152.0/22"
        - "209.85.204.0/22"
        - "35.191.0.0/16"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: present
    
    - name: Create a http health check
      gcp_compute_http_health_check:
        name: kubernetes
        description: "Kubernetes Health Check"
        host: "kubernetes.default.svc.cluster.local"
        request_path: "/healthz"
        healthy_threshold: 10
        port: 80
        timeout_sec: 2
        unhealthy_threshold: 5
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: present
      register: health_check

    - name: Create a target pool
      gcp_compute_target_pool:
        name: kubernetes-target-pool
        health_check: "{{ health_check }}"
#        instances:
#        - controller-0
#        - controller-1
#        - controller-2
        region: "{{ region }}"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: present
      register: targetpool

    - name: Create a forwarding rule
      gcp_compute_forwarding_rule:
        name: kubernetes-forwarding-rule
        region: "{{ region }}"
        target: "{{ targetpool }}"
        ip_protocol: TCP
        port_range: "6443"
        ip_address: "{{ ext_ip.address }}"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: present

#    - name: Create routes
#      gcp_compute_route:
#        name: kubernetes-route-10-200-{{ item }}-0-24
#        dest_range: "10.200.{{ item }}.0/24"
#        next_hop_ip: "10.240.0.2{{ item }}"
#        network: "{{ network }}"        
#        project: "{{ project }}"
#        auth_kind: "{{ cred_kind }}"
#        service_account_file: "{{ cred_file }}"
#        state: present
#      loop: [0,1,2]

    - name: Create controllers
      gcp_compute_instance:
        state: present
        name: "controller-{{ item }}"
        machine_type: n1-standard-1
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              disk_size_gb: 20
              source_image: "{{ image }}"
        network_interfaces:
          - access_configs:
            - name: 'External NAT'
              type: 'ONE_TO_ONE_NAT'
            subnetwork: "{{ subnetwork }}"
            network_ip: "10.240.0.1{{ item }}"
        tags:
          items:
            - kubernetes-the-hard-way
            - controller
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        scopes: "{{ scopes }}"
      loop: [0]

    - name: Create workers
      gcp_compute_instance:
        state: present
        name: "worker-{{ item }}"
        machine_type: n1-standard-1
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              disk_size_gb: 20
              source_image: "{{ image }}"
        network_interfaces:
          - access_configs:
            - name: 'External NAT'
              type: 'ONE_TO_ONE_NAT'
            subnetwork: "{{ subnetwork }}"
            network_ip: "10.240.0.2{{ item }}"
        tags:
          items:
            - kubernetes-the-hard-way
            - worker
        metadata: 
          pod-cidr: 10.200.{{ item }}.0/24 
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        scopes: "{{ scopes }}"
      loop: [0]
