- name: Destroy GCP resources
  hosts: localhost
  gather_facts: no
  tags: destroy
  vars_files:
    - "{{ lookup('env', 'PWD') }}/files/env-vars.yml"

  tasks:
    - name: Delete a controllers instances
      gcp_compute_instance:        
        name: "controller-{{ item }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        scopes: "{{ scopes }}"
        state: absent
      loop: [0,1,2]

    - name: Delete a workers instances
      gcp_compute_instance:        
        name: "worker-{{ item }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        scopes: "{{ scopes }}"
        state: absent
      loop: [0,1,2]

    - name: Delete kubernetes-the-hard-way-allow-internal firewall rule
      gcp_compute_firewall:
        name: kubernetes-the-hard-way-allow-internal
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: absent

    - name: Delete kubernetes-the-hard-way-allow-external firewall rule
      gcp_compute_firewall:
        name: kubernetes-the-hard-way-allow-external
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: absent
    
    - name: Delete kubernetes-the-hard-way-allow-health-check firewall rule
      gcp_compute_firewall:
        name: kubernetes-the-hard-way-allow-health-check
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: absent
    
    - name: Get a subnetwork facts
      gcp_compute_network_facts:
        filters:
        - name = {{ cluster_name }}
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
      register: network

    - name: Delete a subnetwork
      gcp_compute_subnetwork:
        name: kubernetes
        network: "{{ network }}"
        ip_cidr_range: 10.240.0.0/24
        region: "{{ region }}"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: absent

    - name: Delete routes
      gcp_compute_route:
        name: kubernetes-route-10-200-{{ item }}-0-24
        dest_range: "10.200.{{ item }}.0/24"
        network: "{{ network }}"        
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: absent
      loop: [0,1,2]

    - name: Delete a network
      gcp_compute_network:
        name: "{{ cluster_name }}"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: absent

    - name: Delete a forwarding rule
      gcp_compute_forwarding_rule:
        name: kubernetes-forwarding-rule
        region: "{{ region }}"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: absent
    
    - name: Delete a target pool
      gcp_compute_target_pool:
        name: kubernetes-target-pool
        region: "{{ region }}"
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: absent
   
    - name: Delete a http health check
      gcp_compute_http_health_check:
        name: kubernetes
        project: "{{ project }}"
        auth_kind: "{{ cred_kind }}"
        service_account_file: "{{ cred_file }}"
        state: absent
      register: health_check
   
    - name: Delete an ext IP address for instance
      gcp_compute_address:
        name: "{{ cluster_name }}"
        region: "{{ region }}"
        project: "{{ project }}"
        service_account_file: "{{ cred_file }}"
        auth_kind: "{{ cred_kind }}"
        state: absent





