groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'

    - alert: HTTP_responce_time_95th_percentile
      expr: histogram_quantile(0.95,sum(rate(ui_request_response_time_bucket[5m])) by (le)) > 0.08
      labels:
        severity: warning
      annotations:
        description: 'HTTP responce time 95th percentile latency higher than 80ms'
        summary: 'HTTP responce time 95th percentile too high'

