FROM python:3.6-alpine3.6

WORKDIR /app
ADD . /app


RUN apk add --no-cache --virtual .build-deps \
    gcc \
    build-base \
    && pip install --no-cache-dir -r /app/requirements.txt \
    && apk del .build-deps

ENV POST_DATABASE_HOST post_db
ENV POST_DATABASE posts

ENTRYPOINT ["python3", "post_app.py"]
