apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: InfluxDB

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  isDefault: true
  url: http://prometheus:9090
  editable: true

- name: InfluxDB
  type: influxdb
  access: proxy
  database: telegraf
  url: http://influxdb:8086
  editable: true
  jsonData:
    httpMode: GET
