version: '3.3'

services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backend
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_TAG:-1.0}
    ports:
      - ${UI_PORT:-9292}:9292/tcp
    networks:
      - frontend
      
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_TAG:-1.0}
    networks:
      - frontend
      - backend

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_TAG:-1.0}
    networks:
      - frontend
      - backend

volumes:
  post_db:

networks:
  backend:
  frontend:
