plugin: gcp_compute
zones: # populate inventory with instances in these regions
  - europe-west3-a
projects:
  - docker-239809
filters: []
groups:
  awx: "'awx' in name"
scopes:
  - https://www.googleapis.com/auth/compute
service_account_file: service_account.json
auth_kind: serviceaccount
